### ISSUE TITLE
exceptions.AttributeError: CallPopFactory instance has no attribute 'plaintext_login'

### ISSUE THREAD

**Issue by ftoledo** [tipichris/callPopPy#2]
I test on debian stretch and connect to asterisk 11 i setup ami with user and password and get this error:

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 602, in _doReadOrWrite
    why = selectable.doWrite()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 586, in doConnect
    self._connectDone()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 615, in _connectDone
    self.protocol.makeConnection(self)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/protocol.py", line 494, in makeConnection
    self.connectionMade()
  File "/usr/lib/python2.7/dist-packages/starpy/manager.py", line 175, in connectionMade
    if self.factory.plaintext_login:
exceptions.AttributeError: CallPopFactory instance has no attribute 'plaintext_login'

**Comment by tipichris** [comment]
It looks like you're using a different version of starpy to me (I have 1.0.0a13 from http://www.vrplumber.com/programming/starpy/ I think). I'm afraid I don't have time right now to look at this. You could try downgrading starpy, though this might cause problems with more recent versions of Asterisk I guess. I'm using Asterisk 11.7.0

**Comment by tony13tv** [comment]
To the date doing what @tipichris recomends is still a working solution on Ubuntu 20.04.

You have to download [1.0.0a13](https://sourceforge.net/projects/starpy/files/starpy/1.0.0a13/starpy-1.0.0a13.tar.gz/download) and install it.
